default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: <%= ENV['DB_HOST'] || 'localhost'%>
  username: <%= ENV['POSTGRES_USER'] || 'finanza' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'mypassword' %>
  database: <%= ENV['POSTGRES_DB'] || 'cloud_kitchen_dev'%>

development:
  <<: *default

test:
  <<: *default
  database: cloud_kitchen_test

production:
  <<: *default
